<h1><?= __('Our Restaurants') ?></h1>
<?php $viewModel = $this->getViewModelRestaurantsdata(); ?>
<?php if (is_object($viewModel)): ?>
    <?php foreach ($viewModel->getRestaurants() as $restaurant) : ?>
        <?php if ($restaurant->getName()): ?>
            <p><?= __('Name') ?></p>
            <p><b><?= $restaurant->getName() ?></b></p>
        <?php endif; ?>
        <?php if ($restaurant->getCapacity()): ?>
            <p><?= __('Capacity') ?></p>
            <p><b><?= $restaurant->getCapacity() ?></b></p>
        <?php endif; ?>
        <?php if ($restaurant->getLocation()): ?>
            <p><?= __('Location') ?></p>
            <p><b><?= $restaurant->getLocation() ?></b></p>
        <?php endif; ?>
        <?php if ($restaurant->getCreatedAt()): ?>
            <p><?= __('Created at') ?></p>
            <p><b><?= $restaurant->getCreatedAt() ?></b></p>
        <?php endif; ?>
    -------------------------------------------------------
    <?php endforeach; ?>
    <p>
        <a href="<?= $this->getUrl('stoyanov/restaurant/create') ?>"><?= __('Create a new restaurant') ?></a>
    </p>

<?php endif;?>
